version: '3.3'

services:
  helloService:
    container_name: backend_helloService
    image: sonalsrivastava1189/mernwithmicroservices_in_docker:helloService
    command: helloService
    network_mode: host
    environment:
      - PORT=3001

  profileService:
    container_name: backend_profileService
    image: sonalsrivastava1189/mernwithmicroservices_in_docker:profileService
    command: profileService
    network_mode: host
    environment:
      - PORT=3002
      - MONGO_URL=
  frontend:
    container_name: frontend
    image: sonalsrivastava1189/mernwithmicroservices_in_docker:frontend
    command: frontend
    network_mode: host
